### PR TITLE
ecrLogin: support setting registry ids explicitly

### PR DESCRIPTION
**Pull request by alexey-pelykh**
* **Please check if the PR fulfills these requirements**
- [x] The commit message describes your change
- [ ] Tests for the changes have been added if possible (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Support of non-default AWS account for ECR login

* **What is the current behavior?** (You can also link to an open issue here)

ECR login is performed into default AWS account

* **What is the new behavior (if this is a feature change)?**

ECR login is performed into specified AWS account, or default one if not specified

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)

No

* **Other information**:

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
denied: User: arn:aws:iam::AAAAAAAAA:user/infr-ecr-publisher is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-east-1:BBBBBBBBB:repository/xxxxxxx

oh, something else to do I think, but with credentials part I guess

**Comment by alexey-pelykh** [comment]
@hoegertn I hope I did that right :)

**Comment by hoegertn** [comment]
Please rebase on master. The Update branch button does not work for me.

**Comment by alexey-pelykh** [comment]
Done :+1:

**Pull request merged**
