### PR TITLE
Uplift AWS SKD to java 1.11.469

### PR DESCRIPTION
**Pull request by zdtsw**
- Support region for eu-north-1 Stockholm

* **Please check if the PR fulfills these requirements**
- [ ] The commit message describes your change
- [ ] Tests for the changes have been added if possible (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by hoegertn** [comment]
Does not seem to be available yet

**Comment by zdtsw** [comment]
so strange.... from https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111469-2018-12-13  it should be available for a couple of months already

**Comment by zdtsw** [comment]
oh yes, it is my fault.

 the latest release is 1.11.457
https://mvnrepository.com/artifact/org.jenkins-ci.plugins/aws-java-sdk?repo=jenkins-releases

**Comment by zdtsw** [comment]
there already are PR in jenkins-ci-plugin/aws-java-sdk-plugin about uplift aws version, but has not been mergered to master branch. currently, we have to wait for new version of dependency in order to uplift it in pom.
I will close this PR for now

**Pull request closed without merging**
