### PR TITLE
Add setting that enables fetching credentials from node

### PR DESCRIPTION
**Pull request by davegallant**
* **Please check if the PR fulfills these requirements**
- [x] The commit message describes your change
- [x] Tests for the changes have been added if possible (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/jenkinsci/pipeline-aws-plugin/issues/64

* **What is the new behavior (if this is a feature change)?**

1. Adds a global configuration option to always fetch credentials from the current running node. image
2. Adds a `useNode` boolean to `withAWS` that will retrieve credentials from the node in scope

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by tylersouthwick** [comment]
is it possible to do this on a per invocation, or does it have to be a global configuration?

**Comment by davegallant** [comment]
> is it possible to do this per invocation or does it have to be a global configuration? It might make sense to allow this as a setting in the `withAWS` call

Would it make sense to support both cases?
In our particular setup, it is not desired to have the master's instance profile accessible from all nodes.

**Comment by tylersouthwick** [comment]
agree'd. Having a global setting makes sense, and then allowing the node to override.

**Comment by davegallant** [comment]
> agree'd. Having a global setting makes sense, and then allowing the node to override.

Added a `fromNode` boolean to `withAWS()`.

LMKWYT.

**Comment by hoegertn** [comment]
I think I would prefer `useNode` instead.

**Review by tylersouthwick — APPROVED** [review]

**Comment by mihaiplesa** [comment]
Looking forward to this!

**Comment by stilren** [comment]
I am also looking forward to this since it seems to enable us to use the plugin in mainland China. Is there a good way to get an estimate on when this will be released?

**Comment by hoegertn** [comment]
I think I can cut a release this week.

**Comment by stilren** [comment]
@hoegertn You are a star!

**Comment by aliciasteen** [comment]
Is there an estimate for when this will be released?

**Pull request merged**
