### PR TITLE
add PollConfiguration to add timeout configurations

### PR DESCRIPTION
**Pull request by tylersouthwick**
* **Please check if the PR fulfills these requirements**
- [X] The commit message describes your change
- [X] Tests for the changes have been added if possible (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds timeout configuration support in addition to pollInterval configs

* **What is the current behavior?** (You can also link to an open issue here)
timeouts were hardcoded

* **What is the new behavior (if this is a feature change)?**
its customizable

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Comment by hoegertn** [comment]
What is this doing exactly and why is lombok needed for this? Additionally, I did some fixes that broke this PR.

**Comment by tylersouthwick** [comment]
The use case here is that the timeout for some stacks might take a lot longer. Specifically, lambda's within a VPC might take a lot longer.

In general though, the timeout and poll configuration would be good to configure (some large accounts might want to change the polling to be less often due to contention on api throttles).

**Comment by hoegertn** [comment]
Can you please update the README and the changelog? And why is lombok needed as an extra dependency? Is it just to create the builder?

**Comment by hoegertn** [comment]
Thanks for the update. This leaves only the lombok question open...

**Comment by tylersouthwick** [comment]
lombok just removes boiler plate for class definitions and builders. I updated the scope for the library to be provided since it is not needed at runtime, just compile time

**Pull request merged**
