### PR TITLE
Provide S3 Upload from String Source to s3Upload method

### PR DESCRIPTION
**Pull request by helver**
* **Please check if the PR fulfills these requirements**
- [X ] The commit message describes your change
- [X ] Tests for the changes have been added if possible (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)
- [X ] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds the ability to upload a string as an S3 object.  I was unable to find any unit tests that exercise the base functionality of the s3Upload method, so I didn't find any unit tests to replicate in order to test this feature.  I added support for the new optional parameter to the existing unit tests.

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/jenkinsci/pipeline-aws-plugin/issues/122

* **What is the new behavior (if this is a feature change)?**
Add an optional argument to s3Upload that allows user to supply a String. If that argument is present, the upload sends the contents of the String to be injected as the content of the file in S3.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)
Non-breaking. Addition of optional argument.

### CODE REVIEW

**Comment by helver** [comment]
@hoegertn Your feedback would be appreciated.

**Comment by hoegertn** [comment]
I like the idea but I have some comments.

1) It does not make sense to have the parameter `file` set when `text` is specified as it denotes the source file. The target name is the parameter `path`

2) Why do you use a MasterToSlaveCallable to upload text? This could be done directly in the step and without the Uploadmanager. A simple PutObjectRequest should be enough.

**Comment by helver** [comment]
@hoegertn 

Re #1 - I can see that now.  I'll make the change.

Re #2 - You are correct, of course.  I used the MasterToSlaveCallable method simply because that's the way the other methods implemented their behaviors.  I'll do as you suggest and simplify the code.

Thanks very much for the feedback!

**Comment by hoegertn** [comment]
Can you please fix the README and the precondition check too. The rest looks good to me.

**Comment by helver** [comment]
@hoegertn Thanks for the help with this!  I really appreciate your responsiveness.

Any idea when the next release will be?

**Comment by hoegertn** [comment]
I hope to have time to do one this week.

**Comment by webark** [comment]
This appears to be trying to save the file to a `localPath` that is never set, and as mentioned in #196 there is a precondition of a file or path pattern that is still in effect. If there something I'm missing? Would you be open to a PR switching `localPath` to use the `path` and modifying the precondition to see if the `sendingText` is true?

**Pull request merged**
