### PR TITLE
Use more granular dependencies, update parent POM

### PR DESCRIPTION
**Pull request by zbynek**
Removes dependency on the big AWS plugin (300MB .hpi), uses multiple small plugins instead (a few MB).

* **Please check if the PR fulfills these requirements**
- [ ] The commit message describes your change
- [ ] Tests for the changes have been added if possible (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by zbynek** [comment]
@hoegertn I just wanted to build this with Java 11, which needed newer Powermock... seems like getting this plugin compatible with Java 11 is not trivial. I don't want to spend time on something that won't get merged -- I'm wondering if you're still interested in developing this plugin further?

**Comment by hoegertn** [comment]
Thanks for reaching out. I am happy to merge fixes and features to bring value to users. But I currently do not have the setup and bandwidth to do development on my own.

So if you can make it work that would be fantastic and would get merged.

**Comment by zbynek** [comment]
@hoegertn the build is now green.

@Vlatombe for the AWS SDK .jars that do not have their own plugin yet: I think it's easier to add the dependency directly and only wrap it in a plugin when  it's used by more Jenkins plugins. In this PR I've done that for
* aws-java-sdk-elasticloadbalancingv2
* aws-java-sdk-organizations
* aws-java-sdk-cloudfront
* aws-java-sdk-codedeploy
* aws-java-sdk-lambda
* aws-java-sdk-api-gateway
Please let me know if you'd prefer to wrap some/all of these in plugins.

**Comment by basil** [comment]
@hoegertn Thanks for merging this! Looking forward to a release so that Jenkins users may benefit from this change.

**Pull request merged**
