### PR TITLE
Support setting `Content-Encoding` in the `s3Upload` step

### PR DESCRIPTION
**Pull request by thaiphv**
* **Please check if the PR fulfills these requirements**
- [x] The commit message describes your change
- [ ] Tests for the changes have been added if possible (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?**
Feature: Allow `Content-Encoding` header can be specified in the `s3Upload` step.

* **What is the current behavior?** (You can also link to an open issue here)
We can't set the `Content-Encoding` header with the `s3Upload` step.

* **What is the new behavior (if this is a feature change)?**
We can set the `Content-Encoding` header if we want.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)
No.

* **Other information**:
N/A

### CODE REVIEW

**Comment by thaiphv** [comment]
@hoegertn do you mind taking a look at this pull request?

**Comment by hoegertn** [comment]
Looks great. Can you please add the feature to the changelog and the readme documentation?

**Comment by thaiphv** [comment]
> Looks great. Can you please add the feature to the changelog and the readme documentation?
@hoegertn, I'm not sure about the changelog part. Can you take a look again?
Thanks.

**Comment by mojavelinux** [comment]
@thaiphv I tried this and it doesn't seem to work. It's not enough just to set the encoding. The stream actually has to be encoded. So if I set the content encoding to gzip, S3 serves corrupt files. Don't we need to add an encoding step?

**Comment by thaiphv** [comment]
Yes. That's my use case. I gzip'd the files before calling the `s3Upload` step. Think of the step as an interface to the AWS API.

**Comment by mojavelinux** [comment]
I see. Are you uploading files with the gzip extension, or normal files that are gzip'd? I ask because I'm not sure if the transfer manager would get the content type and content size right of the original file. Or does it matter?

Could you share how you gzip'd your files?

For the record, the core S3 plugin supports gzipping the content on the fly. Perhaps that could be considered for this plugin as well.

**Comment by thaiphv** [comment]
I think S3 doesn't really care what's the content type of the objects. If you want to make sure S3 keeps and serves the right content type, you can specify it using the `contentType` argument with the `s3Upload` step. In my case, I don't change the files' extension but only gzip'd them so basically I just use `gzip` and `mv` as below:
```
$ gzip jquery.js && mv jquery.js.gz jquery.js
```
I'm aware that the [s3-plugin](https://github.com/jenkinsci/s3-plugin) does support gzip'ing the files and setting the content encoding to `application/gzip` but it's the only encoding that it supports. With the `contentEncoding` argument, we can specify any encoding and I don't think it's possible to support any encoding that we can specify.

**Pull request merged**
