### PR TITLE
Allow opt out for by default stack creation

### PR DESCRIPTION
**Pull request by indyaah**

### CODE REVIEW

**Comment by hoegertn** [comment]
Can you elaborate on the use case to opt out? And if this should be added, at least the default has to be "create".

**Comment by indyaah** [comment]
Ideally I wanted to have the **_cfnCreate_** as a separate step but I can agree with keeping default to create as it might be a break change (for existing users).

Coming to reasoning for the change;

* In my (limited) experience, when multiple team and devs are independently working on infrastructure it is safer that the job does what it reads (i.e cfnUpdate). 
* One might not want to create the stack if it doesn't exist as it might indicate a problem somewhere else. (i.e A stack that is now missing which was supposed to be there, specially in automated environments)

Also in completely subjective opinion, the updates and creates should be separate tasks/jobs or at least part of parameter. They should be triggered explicitly. i.e I want to create the Stack -> Trigger the job explicitly with parameter "Create" as true and pass it on to plugin.

I apologise for sending out PR in haste without detailed explanation.

**Comment by indyaah** [comment]
Also, while we are on CloudFormation topic, Do you think it's OK to extend step to allow more parameters that `CreateStackRequest` already supports?
I definitely have certain use-cases in mind for adding '--role-arn' support based on experience.

**Comment by hoegertn** [comment]
Thanks for the clarification and for reverting the default. It would not only be a breaking change but be against my intention and understanding of this step.

I see your reasoning and am ok with having the option to disable it, but I disagree that it should be the default.

I see it as following: The step makes sure that the template is applied and after this step, a stack with this state does exist. If this stack has to be updated or created does not matter.

Maybe the name of the step could be better as it is named after an action and not after the desired state.

I would be happy to have additions to the steps with more parameters that may be specified, as long as it does not break the current behavior.

**Comment by indyaah** [comment]
It does make sense to me now that I see it as an action rather than state. I would extend and make PR for supporting more parameters.

PS: I am fixing failing S3 test because of fileseparator along with this PR. If that's ok with you

**Comment by hoegertn** [comment]
This would be great. Started to use CI today and it runs on windows too.

**Comment by indyaah** [comment]
@hoegertn : Just FYI, the issues runs bit deeper than tests. The problem lies with implementation reliance on java DefaultFileSystem. You should mention on the main page that the plugin should not be used with Windows based Jenkins and S3* steps.

**Comment by hoegertn** [comment]
Ok, so please just disable the test. I pinged the author of the S3FindFiles step about the Windows issue.

**Comment by hoegertn** [comment]
Please rebase onto master, as the build is fixed.

**Comment by hoegertn** [comment]
This now conflicts due to the roleArn changes

**Comment by hoegertn** [comment]
Please add documentation and a changelog entry

**Comment by indyaah** [comment]
Yeah, completely missed that it might have conflicts due to same file. 
I am currently updating documentation.

**Comment by hoegertn** [comment]
Thanks for the docs. Something broke the README file and it is now twice the content in the same file.

**Comment by indyaah** [comment]
I guess it was merging/rebasing issue. Fixed it.

**Pull request merged**
