### PR TITLE
Add step: s3FindFiles

### PR DESCRIPTION
**Pull request by tekkamanendless**
One of the things that's missing here is the ability to _query_ S3 for what's already there.  Jenkins already has a step called `findFiles` that is provided by the `pipeline-utility-steps-plugin` plugin.  This code adds analogous functionality via `s3FindFiles`, even returning the same data structure.

From `s3FindFiles` in the README:

---

This provides a way to query the files/folders in the S3 bucket, analogous to the `findFiles` step provided by "pipeline-utility-steps-plugin".
If specified, the `path` limits the scope of the operation to that folder only.
The `glob` parameter tells `s3FindFiles` what to look for.  This can be a file name, a full path to a file, or a standard glob ("\*", "\*.ext", "path/\*\*/file.ext", etc.).

If you do not specify `path`, then it will default to the root of the bucket.
The path is assumed to be a folder; you do not need to end it with a "/", but it is okay if you do.

If you do not specify `glob`, then it will default to "\*".

By default, this will return both files and folders.
To only return files, set the `onlyFiles` parameter to `true`.

```
files = s3FindFiles(bucket:'my-bucket')
files = s3FindFiles(bucket:'my-bucket', glob:'path/to/targetFolder/file.ext')
files = s3FindFiles(bucket:'my-bucket', path:'path/to/targetFolder', glob:'file.ext')
files = s3FindFiles(bucket:'my-bucket', path:'path/to/targetFolder', glob:'*.ext')
files = s3FindFiles(bucket:'my-bucket', path:'path', glob:'**/file.ext')
```

`s3FindFiles` returns an array of `FileWrapper` objects exactly identical to those returned by `findFiles`.

Each `FileWrapper` object has the following properties:

* `name`: the filename portion of the path (for "path/to/my/file.ext", this would be "file.ext")
* `path`: the full path of the file (for "path/to/my/file.ext", this would be "path/to/my/file.ext")
* `directory`: true if this is a directory; false otherwise
* `length`: the length of the file (this is always "0" for directories)
* `lastModified`: the last modification timestamp, in milliseconds since the Unix epoch (this is always "0" for directories)

When used in a string context, a `FileWrapper` object returns the value of its `path`.

### CODE REVIEW

**Comment by hoegertn** [comment]
Great addition. Could you please add a line to the changelog?

**Comment by tekkamanendless** [comment]
Okay, I slept on this, and I want to have the "path" returned be relative
to the "path" parameter.  This way, the path returned maps 1:1 with the
glob (as opposed to being absolute in the bucket).  I'll have a commit up
today with the change.

**Comment by tekkamanendless** [comment]
Okay, the resulting `path` properties are now _relative_ to the input `path` parameter, and I like it a lot better.

Also, I did some small refactoring so that I could have a few more tests around `s3FindFiles`, since it's a bit more complicated than I had originally thought.

**Comment by hoegertn** [comment]
@tekkamanendless Your tests for the S3FindFiles seem to fail on Windows machines.

```
07:31:20 [windows-8] Failed tests: 
07:31:20 [windows-8] de.taimos.pipeline.aws.S3FindFilesStepTest.createFileWrapperFromFile(de.taimos.pipeline.aws.S3FindFilesStepTest)
07:31:20 [windows-8]   Run 1: S3FindFilesStepTest.createFileWrapperFromFile:141 expected:<path[/to/my/]file.ext> but was:<path[\to\my\]file.ext>
07:31:20 [windows-8]   Run 2: S3FindFilesStepTest.createFileWrapperFromFile:141 expected:<path[/to/my/]file.ext> but was:<path[\to\my\]file.ext>
07:31:20 [windows-8]   Run 3: S3FindFilesStepTest.createFileWrapperFromFile:141 expected:<path[/to/my/]file.ext> but was:<path[\to\my\]file.ext>
07:31:20 [windows-8]   Run 4: S3FindFilesStepTest.createFileWrapperFromFile:141 expected:<path[/to/my/]file.ext> but was:<path[\to\my\]file.ext>
07:31:20 [windows-8]   Run 5: S3FindFilesStepTest.createFileWrapperFromFile:141 expected:<path[/to/my/]file.ext> but was:<path[\to\my\]file.ext>
07:31:20 [windows-8] 
07:31:20 [windows-8] de.taimos.pipeline.aws.S3FindFilesStepTest.createFileWrapperFromFolder(de.taimos.pipeline.aws.S3FindFilesStepTest)
07:31:20 [windows-8]   Run 1: S3FindFilesStepTest.createFileWrapperFromFolder:104 expected:<path[/to/]folder/> but was:<path[\to\]folder/>
07:31:20 [windows-8]   Run 2: S3FindFilesStepTest.createFileWrapperFromFolder:104 expected:<path[/to/]folder/> but was:<path[\to\]folder/>
07:31:20 [windows-8]   Run 3: S3FindFilesStepTest.createFileWrapperFromFolder:104 expected:<path[/to/]folder/> but was:<path[\to\]folder/>
07:31:20 [windows-8]   Run 4: S3FindFilesStepTest.createFileWrapperFromFolder:104 expected:<path[/to/]folder/> but was:<path[\to\]folder/>
07:31:20 [windows-8]   Run 5: S3FindFilesStepTest.createFileWrapperFromFolder:104 expected:<path[/to/]folder/> but was:<path[\to\]folder/>
```

Would you mind having a look?

**Comment by tekkamanendless** [comment]
I'll try to poke around a bit this weekend.  Looks like some basic path-separator stuff.

**Comment by tekkamanendless** [comment]
Okay, I have another pull request to address the Windows path issue: https://github.com/jenkinsci/pipeline-aws-plugin/pull/19

**Pull request merged**
